### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by camster91** [jdelkins/deluge-autoreannounce#1]
Hello! Just wondering if there is a way to install this plugin on a windows machine? Thanks!

**Comment by jdelkins** [comment]
Hi, sorry I haven't used this in many years, and never on Windows. It probably needs updating due to newer versions of deluge. I don't have time to look into it either.

I guess if you want to try to use it, check out the repo somewhere and try to reproduce the steps in `create_dev_link.sh` script. That script is obviously for bourne shell, but it's not very complicated. Basically it just does `python setup.py build develop`, and then copies the `.egg-link` file into the deluge plugins directory.

**Comment by camster91** [comment]
No problem. Thanks!

**Comment by jdelkins** [comment]
Good luck. If you are able to get it working, feel free to submit a PR.
